trigger:
- none

parameters:
- name: environment
  displayName: Environment
  type: string
  default: 'qa'
  values:
  - 'dev'
  - 'qa'
  - 'uat'

- name: scanType
  displayName: Type of ZAP scan
  type: string
  default: 'baseline'
  values:
  - 'baseline'
  - 'full'

- name: reportTemplate
  displayName: ZAP Report Template
  type: string
  default: 'traditional-html'
  values:
  - traditional-html
  - traditional-json
  - sarif-json
  - traditional-pdf

variables:
  # Base URLs for each environment
  dev_admin_base: 'https://dev.app-np.neovance.com'
  dev_agent_base: 'https://dev-agent.app-np.neovance.com'
  qa_admin_base: 'https://qa.app-np.neovance.com'
  qa_agent_base: 'https://qa-agent.app-np.neovance.com'
  uat_admin_base: 'https://uat.app-np.neovance.com'
  uat_agent_base: 'https://uat-agent.app-np.neovance.com'

  # Common URL paths
  admin_paths: >
    /clients,
    /user-management/permission-sets,
    /entity-manager,
    /hcp-portal,
    /case-mapping,
    /correspondence/placeholders,
    /correspondence/static-documents,
    /correspondence/document-management,
    /correspondence/template-management,
    /correspondence/send-manual-communication,
    /correspondence/correspondence-logs,
    /sla-management,
    /consent-configuration,
    /profile-details

  agent_paths: >
    /dashboard,
    /entities/2144,
    /my-cases/32/1395/36,
    /my-tasks/1127/1318/37,
    /manage-queue/dynamic-queue/32/1394/207,
    /manage-queue/dynamic-queue/32/1394/2,
    /correspondence/correspondence-logs/outbound/3607,
    /interaction,
    /permission-assignment

stages:
- stage: Auth_Login
  displayName: "Authenticate via Playwright"
  jobs:
  - job: PlaywrightLoginAdmin
    displayName: "Run Playwright login and save session (Admin)"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseNode@1
      inputs:
        version: '18.x'
    - script: |
        npm install -D @playwright/test
        npx playwright install --with-deps
        mkdir -p $(Build.ArtifactStagingDirectory)/auth
        
        # Get base URL for selected environment
        if [ "$ENVIRONMENT" = "dev" ]; then
          BASE_URL="$(dev_admin_base)"
          ADMIN_EMAIL="$(dev_ADMIN_EMAIL)"
          ADMIN_PASSWORD="$(dev_ADMIN_PASSWORD)"
          ADMIN_MFA_SECRET="$(dev_ADMIN_MFA_SECRET)"
        elif [ "$ENVIRONMENT" = "qa" ]; then
          BASE_URL="$(qa_admin_base)"
          ADMIN_EMAIL="$(qa_ADMIN_EMAIL)"
          ADMIN_PASSWORD="$(qa_ADMIN_PASSWORD)"
          ADMIN_MFA_SECRET="$(qa_ADMIN_MFA_SECRET)"
        else
          BASE_URL="$(uat_admin_base)"
          ADMIN_EMAIL="$(uat_ADMIN_EMAIL)"
          ADMIN_PASSWORD="$(uat_ADMIN_PASSWORD)"
          ADMIN_MFA_SECRET="$(uat_ADMIN_MFA_SECRET)"
        fi
        
        node playwright-login.js \
          --url "$BASE_URL" \
          --email "$ADMIN_EMAIL" \
          --password "$ADMIN_PASSWORD" \
          --mfaSecret "$ADMIN_MFA_SECRET" \
          --output "$(Build.ArtifactStagingDirectory)/auth/admin-session.json"
      env:
        ENVIRONMENT: ${{ parameters.environment }}
        dev_admin_base: $(dev_admin_base)
        qa_admin_base: $(qa_admin_base)
        uat_admin_base: $(uat_admin_base)
        dev_ADMIN_EMAIL: $(dev_ADMIN_EMAIL)
        dev_ADMIN_PASSWORD: $(dev_ADMIN_PASSWORD)
        dev_ADMIN_MFA_SECRET: $(dev_ADMIN_MFA_SECRET)
        qa_ADMIN_EMAIL: $(qa_ADMIN_EMAIL)
        qa_ADMIN_PASSWORD: $(qa_ADMIN_PASSWORD)
        qa_ADMIN_MFA_SECRET: $(qa_ADMIN_MFA_SECRET)
        uat_ADMIN_EMAIL: $(uat_ADMIN_EMAIL)
        uat_ADMIN_PASSWORD: $(uat_ADMIN_PASSWORD)
        uat_ADMIN_MFA_SECRET: $(uat_ADMIN_MFA_SECRET)
      displayName: "Run Playwright login (Admin)"
    - publish: '$(Build.ArtifactStagingDirectory)/auth/admin-session.json'
      artifact: 'PlaywrightSessionAdmin'
      displayName: 'Publish Admin session.json'

  - job: PlaywrightLoginAgent
    displayName: "Run Playwright login and save session (Agent)"
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: UseNode@1
      inputs:
        version: '18.x'
    - script: |
        npm install -D @playwright/test
        npx playwright install --with-deps
        mkdir -p $(Build.ArtifactStagingDirectory)/auth
        
        # Get base URL for selected environment
        if [ "$ENVIRONMENT" = "dev" ]; then
          BASE_URL="$(dev_agent_base)"
          AGENT_EMAIL="$(dev_AGENT_EMAIL)"
          AGENT_PASSWORD="$(dev_AGENT_PASSWORD)"
          AGENT_MFA_SECRET="$(dev_AGENT_MFA_SECRET)"
        elif [ "$ENVIRONMENT" = "qa" ]; then
          BASE_URL="$(qa_agent_base)"
          AGENT_EMAIL="$(qa_AGENT_EMAIL)"
          AGENT_PASSWORD="$(qa_AGENT_PASSWORD)"
          AGENT_MFA_SECRET="$(qa_AGENT_MFA_SECRET)"
        else
          BASE_URL="$(uat_agent_base)"
          AGENT_EMAIL="$(uat_AGENT_EMAIL)"
          AGENT_PASSWORD="$(uat_AGENT_PASSWORD)"
          AGENT_MFA_SECRET="$(uat_AGENT_MFA_SECRET)"
        fi
        
        node playwright-login.js \
          --url "$BASE_URL" \
          --email "$AGENT_EMAIL" \
          --password "$AGENT_PASSWORD" \
          --mfaSecret "$AGENT_MFA_SECRET" \
          --output "$(Build.ArtifactStagingDirectory)/auth/agent-session.json"
      env:
        ENVIRONMENT: ${{ parameters.environment }}
        dev_agent_base: $(dev_agent_base)
        qa_agent_base: $(qa_agent_base)
        uat_agent_base: $(uat_agent_base)
        dev_AGENT_EMAIL: $(dev_AGENT_EMAIL)
        dev_AGENT_PASSWORD: $(dev_AGENT_PASSWORD)
        dev_AGENT_MFA_SECRET: $(dev_AGENT_MFA_SECRET)
        qa_AGENT_EMAIL: $(qa_AGENT_EMAIL)
        qa_AGENT_PASSWORD: $(qa_AGENT_PASSWORD)
        qa_AGENT_MFA_SECRET: $(qa_AGENT_MFA_SECRET)
        uat_AGENT_EMAIL: $(uat_AGENT_EMAIL)
        uat_AGENT_PASSWORD: $(uat_AGENT_PASSWORD)
        uat_AGENT_MFA_SECRET: $(uat_AGENT_MFA_SECRET)
      displayName: "Run Playwright login (Agent)"
    - publish: '$(Build.ArtifactStagingDirectory)/auth/agent-session.json'
      artifact: 'PlaywrightSessionAgent'
      displayName: 'Publish Agent session.json'

- stage: ZAP_Scan_Stage
  displayName: "Run ZAP Scan"
  dependsOn: Auth_Login
  jobs:
  - job: AdminScan
    displayName: "ZAP Scan - Admin"
    variables:
      baseUrl: $(${{ parameters.environment }}_admin_base)
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: PlaywrightSessionAdmin
    - bash: |
        # Combine base URL with paths
        FULL_URLS=$(echo "$(admin_paths)" | tr ',' '\n' | sed 's/^[ \t]*//' | sed "s|^|$(baseUrl)|" | tr '\n' ',' | sed 's/,$//')
      name: SetUrls
    - template: zap-template.yml
      parameters:
        targetUrls: $(SetUrls.FULL_URLS)
        appName: 'admin'
        scanType: ${{ parameters.scanType }}
        reportTemplate: ${{ parameters.reportTemplate }}

  - job: AgentScan
    displayName: "ZAP Scan - Agent"
    variables:
      baseUrl: $(${{ parameters.environment }}_agent_base)
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - download: current
      artifact: PlaywrightSessionAgent
    - bash: |
        # Combine base URL with paths
        FULL_URLS=$(echo "$(agent_paths)" | tr ',' '\n' | sed 's/^[ \t]*//' | sed "s|^|$(baseUrl)|" | tr '\n' ',' | sed 's/,$//')
      name: SetUrls
    - template: zap-template.yml
      parameters:
        targetUrls: $(SetUrls.FULL_URLS)
        appName: 'agent'
        scanType: ${{ parameters.scanType }}
        reportTemplate: ${{ parameters.reportTemplate }}